export const functional = {
  Tab: 'Tab',
  CapsLock: 'Caps',
  Enter: 'Enter',
  ShiftLeft: 'Shift',
  ArrowUp: '\u2191',
  ShiftRight: 'Shift',
  ControlLeft: 'Ctrl',
  AltLeft: 'Alt',
  Space: '',
  AltRight: 'Alt',
  ControlRight: 'Ctrl',
  ArrowLeft: '\u2190',
  ArrowDown: '\u2193',
  ArrowRight: '\u2192',
  Backspace: 'Backspace',
  Del: 'Del',
};
